const defaultCars=[{id:1,n:'پژو 207 اتوماتیک',y:'۱۴۰۲',k:'۳۵,۰۰۰',p:'۱,۲۵۰,۰۰۰,۰۰۰ تومان',city:'تهران',t:['اتوماتیک','کم‌کارکرد'],i:'🚗',photos:[],fuel:'بنزین',gear:'اتوماتیک',color:'سفید',desc:'خودروی تمیز و کم‌کارکرد، مناسب استفاده شهری.'},{id:2,n:'دنا پلاس توربو',y:'۱۴۰۱',k:'۵۲,۰۰۰',p:'۹۸۰,۰۰۰,۰۰۰ تومان',city:'اهواز',t:['اتوماتیک'],i:'🚘',photos:[],fuel:'بنزین',gear:'اتوماتیک',color:'مشکی',desc:'دنا پلاس توربو با وضعیت فنی مناسب.'},{id:3,n:'سمند LX',y:'۱۳۹۹',k:'۸۰,۰۰۰',p:'۶۲۰,۰۰۰,۰۰۰ تومان',city:'شیراز',t:['اقتصادی'],i:'🚙',photos:[],fuel:'بنزین',gear:'دستی',color:'نقره‌ای',desc:'خودروی اقتصادی و مناسب مصرف روزانه.'},{id:4,n:'BMW 320i',y:'۲۰۱۹',k:'۴۵,۰۰۰',p:'۴,۸۵۰,۰۰۰,۰۰۰ تومان',city:'تهران',t:['لوکس','اتوماتیک'],i:'🏎️',photos:[],fuel:'بنزین',gear:'اتوماتیک',color:'مشکی',desc:'BMW 320i با امکانات کامل و کارکرد پایین.'},{id:5,n:'پژو پارس',y:'۱۴۰۰',k:'۶۰,۰۰۰',p:'۷۲۰,۰۰۰,۰۰۰ تومان',city:'اهواز',t:['اقتصادی'],i:'🚗',photos:[],fuel:'بنزین',gear:'دستی',color:'سفید',desc:'پژو پارس سالم و آماده انتقال.'},{id:6,n:'تویوتا RAV4',y:'۲۰۲۰',k:'۳۸,۰۰۰',p:'۵,۶۰۰,۰۰۰,۰۰۰ تومان',city:'مشهد',t:['شاسی بلند','کم‌کارکرد'],i:'🚙',photos:[],fuel:'بنزین',gear:'اتوماتیک',color:'سفید',desc:'شاسی‌بلند کم‌کارکرد با وضعیت بسیار خوب.'}];
let cars=JSON.parse(localStorage.getItem('carivoCars')||'null')||defaultCars;let favorites=JSON.parse(localStorage.getItem('carivoFavorites')||'[]');let selectedPhotos=[];let currentUser=null;
const grid=document.querySelector('#grid'),empty=document.querySelector('#empty');
function render(list=cars){grid.innerHTML=list.map(c=>`<article class="card" data-id="${c.id}"><div class="pic">${c.photos?.[0]?`<img src="${c.photos[0]}">`:c.i||'🚗'}<button class="fav-card" data-fav="${c.id}">${favorites.includes(c.id)?'♥':'♡'}</button></div><div class="body"><h3>${c.n}</h3><div class="meta">${c.y} • ${c.k} کیلومتر • ${c.city||'ایران'}</div><div class="price">${c.p}</div><button class="details" data-detail="${c.id}">مشاهده جزئیات ←</button></div></article>`).join('');empty.hidden=list.length>0;bindCards()}
function bindCards(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetails(Number(b.dataset.detail)));document.querySelectorAll('.card').forEach(c=>c.onclick=e=>{if(!e.target.dataset.fav&&!e.target.closest('.details'))showDetails(Number(c.dataset.id))});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(Number(b.dataset.fav))})}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('carivoFavorites',JSON.stringify(favorites));render(cars)}
function search(q){q=q.trim().toLowerCase();render(!q?cars:cars.filter(c=>(c.n+' '+c.t.join(' ')+' '+(c.city||'')).toLowerCase().includes(q)));document.querySelector('#cars').scrollIntoView({behavior:'smooth'})}
document.querySelector('#search').onclick=()=>search(document.querySelector('#q').value);document.querySelector('#q').onkeydown=e=>{if(e.key==='Enter')search(e.target.value)};document.querySelectorAll('[data-q]').forEach(x=>x.onclick=()=>{document.querySelector('#q').value=x.dataset.q;search(x.dataset.q)});document.querySelector('#all').onclick=()=>{document.querySelector('#q').value='';render()};document.querySelectorAll('[data-f]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-f]').forEach(b=>b.classList.remove('active'));x.classList.add('active');render(x.dataset.f==='all'?cars:cars.filter(c=>c.t.includes(x.dataset.f)))});
const modal=document.querySelector('#modal');function open(t){document.querySelector('#mt').textContent=t;modal.hidden=false}document.querySelector('#post').onclick=()=>currentUser?open('ثبت آگهی جدید'):openAuth('login');document.querySelector('#cta').onclick=()=>currentUser?open('ثبت آگهی جدید'):openAuth('login');document.querySelector('#close').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};
const photoInput=document.querySelector('#adPhotos'),preview=document.querySelector('#preview');document.querySelector('#photoButton').onclick=()=>photoInput.click();photoInput.onchange=()=>{selectedPhotos=[];preview.innerHTML='';[...photoInput.files].slice(0,6).forEach(file=>{const reader=new FileReader();reader.onload=e=>{selectedPhotos.push(e.target.result);const img=document.createElement('img');img.src=e.target.result;preview.appendChild(img)};reader.readAsDataURL(file)})};
document.querySelector('#adForm').onsubmit=async e=>{e.preventDefault();if(!currentUser){modal.hidden=true;openAuth('login');return}const c={id:Date.now(),n:document.querySelector('#adTitle').value,y:document.querySelector('#adYear').value,k:document.querySelector('#adKm').value,p:document.querySelector('#adPrice').value,city:document.querySelector('#adCity').value,t:[],i:'🚗',photos:selectedPhotos,fuel:'بنزین',gear:'نامشخص',color:'نامشخص',desc:document.querySelector('#adDesc').value||'آگهی ثبت‌شده توسط کاربر',sellerId:currentUser.id,sellerName:currentUser.user_metadata?.full_name||currentUser.email};cars.unshift(c);localStorage.setItem('carivoCars',JSON.stringify(cars));try{await saveListingToSupabase(c)}catch(err){console.warn(err)}render();modal.hidden=true;e.target.reset();selectedPhotos=[];preview.innerHTML='';document.querySelector('#cars').scrollIntoView({behavior:'smooth'});alert('آگهی با موفقیت ثبت شد.');};
async function saveListingToSupabase(c){if(!window.carivoSupabase)return;const price=Number(String(c.p).replace(/[^0-9]/g,''))||null;const {data,error}=await window.carivoSupabase.from('listings').insert({seller_id:c.sellerId,title:c.n,year:c.y,mileage:c.k,price,city:c.city,fuel:c.fuel,transmission:c.gear,color:c.color,description:c.desc}).select().single();if(error)throw error;if(c.photos?.length)console.log('عکس‌ها بعد از اتصال Storage آپلود می‌شوند',data.id)}
function showDetails(id){const c=cars.find(x=>x.id===id);if(!c)return;document.querySelector('#detailTitle').textContent=c.n;document.querySelector('#detailPrice').textContent=c.p;document.querySelector('#detailCity').textContent=c.city||'ایران';document.querySelector('#detailDesc').textContent=c.desc||'توضیحی برای این آگهی ثبت نشده است.';document.querySelector('#detailSpecs').innerHTML=[['سال ساخت',c.y],['کارکرد',c.k+' کیلومتر'],['گیربکس',c.gear||'نامشخص'],['سوخت',c.fuel||'نامشخص'],['رنگ',c.color||'نامشخص'],['فروشنده',c.sellerName||'فروشنده کاریوو']].map(x=>`<div><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');const main=document.querySelector('#detailImage'),thumbs=document.querySelector('#detailThumbs');thumbs.innerHTML='';const photos=c.photos||[];main.innerHTML=photos[0]?`<img src="${photos[0]}">`:(c.i||'🚗');photos.forEach(p=>{const im=document.createElement('img');im.src=p;im.onclick=()=>main.innerHTML=`<img src="${p}">`;thumbs.appendChild(im)});document.querySelector('#detailFav').textContent=favorites.includes(c.id)?'♥ ذخیره شده':'♡ ذخیره آگهی';document.querySelector('#detailFav').onclick=()=>{toggleFavorite(c.id);showDetails(id)};document.querySelector('#detailShare').onclick=async()=>{try{await navigator.clipboard.writeText(location.href+'#car-'+id);alert('لینک آگهی کپی شد.')}catch{alert('امکان کپی لینک وجود ندارد.')}};document.querySelector('#detailContact').onclick=()=>alert('در نسخه بعدی، تماس و چت با فروشنده را اضافه می‌کنیم.');document.querySelector('#detailsModal').hidden=false;location.hash='car-'+id}
document.querySelector('#detailClose').onclick=()=>{document.querySelector('#detailsModal').hidden=true;history.replaceState(null,'',location.pathname+location.search)};document.querySelector('#detailsModal').onclick=e=>{if(e.target===document.querySelector('#detailsModal'))document.querySelector('#detailsModal').hidden=true};document.querySelector('#theme').onclick=()=>{document.body.classList.toggle('dark');document.querySelector('#theme').textContent=document.body.classList.contains('dark')?'🌙':'☀️'};

// Supabase Auth: email/password registration, login, profile and logout.
const authModal=document.querySelector('#authModal'),authContent=document.querySelector('#authContent'),authClose=document.querySelector('#authClose');
function openAuth(mode='login'){authContent.innerHTML=mode==='signup'?`<span class="badge">عضویت در Carivo</span><h2>ساخت حساب کاربری</h2><form id="signupForm"><label>نام و نام خانوادگی<input id="signupName" required placeholder="مثلاً مانی فرحان"></label><label>ایمیل<input id="signupEmail" type="email" required placeholder="name@example.com"></label><label>رمز عبور<input id="signupPassword" type="password" minlength="6" required placeholder="حداقل ۶ کاراکتر"></label><button class="primary" type="submit">ثبت‌نام</button></form><p>قبلاً حساب داری؟ <button class="auth-link" id="toLogin">ورود</button></p>`:`<span class="badge">ورود به Carivo</span><h2>خوش برگشتی 👋</h2><form id="loginForm"><label>ایمیل<input id="loginEmail" type="email" required placeholder="name@example.com"></label><label>رمز عبور<input id="loginPassword" type="password" required placeholder="رمز عبور"></label><button class="primary" type="submit">ورود</button></form><p>حساب نداری؟ <button class="auth-link" id="toSignup">ثبت‌نام کن</button></p><p><button class="auth-link" id="forgot">فراموشی رمز عبور</button></p>`;authModal.hidden=false;document.querySelector('#toSignup')?.addEventListener('click',()=>openAuth('signup'));document.querySelector('#toLogin')?.addEventListener('click',()=>openAuth('login'));document.querySelector('#forgot')?.addEventListener('click',forgotPassword);document.querySelector('#loginForm')?.addEventListener('submit',login);document.querySelector('#signupForm')?.addEventListener('submit',signup)}
authClose.onclick=()=>authModal.hidden=true;authModal.onclick=e=>{if(e.target===authModal)authModal.hidden=true};
async function signup(e){e.preventDefault();if(!window.carivoSupabase)return alert('اتصال دیتابیس آماده نیست.');const name=document.querySelector('#signupName').value.trim(),email=document.querySelector('#signupEmail').value.trim(),password=document.querySelector('#signupPassword').value;const {data,error}=await window.carivoSupabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)return alert(error.message);if(data.user){const {error:profileError}=await window.carivoSupabase.from('profiles').upsert({id:data.user.id,full_name:name});if(profileError)console.warn(profileError)}if(data.session){currentUser=data.user;authModal.hidden=true;updateAuthUI()}else{alert('ثبت‌نام انجام شد. اگر تأیید ایمیل فعال باشد، ایمیل خود را تأیید کن و سپس وارد شو.');openAuth('login')}}
async function login(e){e.preventDefault();if(!window.carivoSupabase)return alert('اتصال دیتابیس آماده نیست.');const email=document.querySelector('#loginEmail').value.trim(),password=document.querySelector('#loginPassword').value;const {data,error}=await window.carivoSupabase.auth.signInWithPassword({email,password});if(error)return alert(error.message);currentUser=data.user;await ensureProfile();authModal.hidden=true;updateAuthUI()}
async function forgotPassword(){const email=prompt('ایمیل حساب Carivo را وارد کن:');if(!email)return;const {error}=await window.carivoSupabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});alert(error?error.message:'لینک بازیابی رمز عبور ارسال شد.')}
async function ensureProfile(){if(!currentUser)return;const name=currentUser.user_metadata?.full_name||currentUser.email?.split('@')[0]||'کاربر Carivo';await window.carivoSupabase.from('profiles').upsert({id:currentUser.id,full_name:name})}
async function logout(){await window.carivoSupabase.auth.signOut();currentUser=null;updateAuthUI()}
function updateAuthUI(){const btn=document.querySelector('#login');if(!btn)return;if(currentUser){const name=currentUser.user_metadata?.full_name||currentUser.email?.split('@')[0]||'حساب من';btn.textContent='👤 '+name;btn.onclick=()=>openProfile()}else{btn.textContent='ورود';btn.onclick=()=>openAuth('login')}}
function openProfile(){authContent.innerHTML=`<span class="badge">حساب کاربری</span><h2>سلام ${currentUser?.user_metadata?.full_name||'دوست Carivo'} 👋</h2><p>${currentUser?.email||''}</p><button class="primary" id="logoutBtn">خروج از حساب</button>`;authModal.hidden=false;document.querySelector('#logoutBtn').onclick=()=>{authModal.hidden=true;logout()}}
(async()=>{if(window.supabase&&window.CARIVO_SUPABASE_URL&&window.CARIVO_SUPABASE_ANON_KEY){window.carivoSupabase=window.supabase.createClient(window.CARIVO_SUPABASE_URL,window.CARIVO_SUPABASE_ANON_KEY);const {data}=await window.carivoSupabase.auth.getSession();currentUser=data.session?.user||null;window.carivoSupabase.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;updateAuthUI()});if(currentUser)await ensureProfile()}updateAuthUI();render()})();