// Carivo authentication v2: name + mobile + password, no SMS OTP
(function(){
  const sb=()=>window.carivoSupabase;
  const authModal=document.querySelector('#authModal'), authContent=document.querySelector('#authContent');
  function normalizePhone(v){v=(v||'').replace(/[\s-]/g,'');if(v.startsWith('09'))return '+98'+v.slice(1);if(v.startsWith('9')&&v.length===10)return '+98'+v;if(v.startsWith('+98'))return v;return v}
  function showAuth(mode='login'){
    authContent.innerHTML=`<span class="badge">ورود به Carivo</span><h2>${mode==='login'?'ورود':'ثبت‌نام'}</h2><form id="authForm">${mode==='signup'?'<label>نام و نام خانوادگی<input id="fullName" autocomplete="name" required placeholder="مثلاً مانی فرحان"></label>':''}<label>شماره موبایل<input id="phoneNumber" inputmode="tel" autocomplete="tel" required placeholder="0912 123 4567"></label><label>رمز عبور<input id="password" type="password" autocomplete="current-password" minlength="6" required placeholder="حداقل ۶ کاراکتر"></label><button class="primary" type="submit">${mode==='login'?'ورود':'ساخت حساب'}</button></form><button class="auth-link" id="switchAuth">${mode==='login'?'ثبت‌نام حساب جدید':'قبلاً حساب دارم'}</button>`;
    authModal.hidden=false;document.querySelector('#authForm').onsubmit=e=>submitAuth(e,mode);document.querySelector('#switchAuth').onclick=()=>showAuth(mode==='login'?'signup':'login');
  }
  async function submitAuth(e,mode){e.preventDefault();const phone=normalizePhone(document.querySelector('#phoneNumber').value),password=document.querySelector('#password').value;if(!/^\+989\d{9}$/.test(phone))return alert('شماره موبایل ایران را به‌صورت 09xxxxxxxxx وارد کن.');if(!sb())return alert('اتصال Supabase آماده نیست.');const email=phone.replace('+','')+'@carivo.local';let result;if(mode==='signup'){result=await sb().auth.signUp({email,password,options:{data:{full_name:document.querySelector('#fullName').value.trim(),phone}}})}else{result=await sb().auth.signInWithPassword({email,password})}if(result.error)return alert(result.error.message);const user=result.data.user;if(mode==='signup'){await sb().from('profiles').upsert({id:user.id,full_name:document.querySelector('#fullName').value.trim(),phone});alert('حساب ساخته شد. حالا با شماره موبایل و رمز عبور وارد شو.');showAuth('login');return}authModal.hidden=true;window.currentUser=user;if(typeof updateAuthUI==='function')updateAuthUI()}
  async function init(){if(!sb())return;const {data}=await sb().auth.getSession();window.currentUser=data.session?.user||null;if(typeof updateAuthUI==='function')updateAuthUI();sb().auth.onAuthStateChange((_event,session)=>{window.currentUser=session?.user||null;if(typeof updateAuthUI==='function')updateAuthUI()})}
  window.openPhoneAuth=()=>showAuth('login');document.querySelector('#authClose')?.addEventListener('click',()=>authModal.hidden=true);init();
})();