// Carivo authentication v4: PHONE + PASSWORD ONLY. No email and no OTP.
(function(){
 const sb=()=>window.carivoSupabase;
 const modal=document.querySelector('#authModal'), box=document.querySelector('#authContent');
 const phone=v=>(v||'').replace(/[\s-]/g,'').replace(/^09/,'+98 9').replace(/\s/g,'');
 function form(mode){box.innerHTML=`<span class="badge">Carivo</span><h2>${mode==='signup'?'ثبت‌نام':'ورود'}</h2><form id="authForm">${mode==='signup'?'<label>نام و نام خانوادگی<input id="fullName" required autocomplete="name" placeholder="نام و نام خانوادگی"></label>':''}<label>شماره موبایل<input id="phoneNumber" required inputmode="tel" autocomplete="tel" placeholder="0912 123 4567"></label><label>رمز عبور<input id="password" required type="password" minlength="6" autocomplete="current-password" placeholder="حداقل ۶ کاراکتر"></label><button class="primary" type="submit">${mode==='signup'?'ساخت حساب':'ورود به حساب'}</button></form><button class="auth-link" id="switchAuth">${mode==='signup'?'قبلاً حساب دارم':'ثبت‌نام حساب جدید'}</button>`;modal.hidden=false;document.querySelector('#authForm').onsubmit=e=>submit(e,mode);document.querySelector('#switchAuth').onclick=()=>form(mode==='signup'?'login':'signup')}
 async function submit(e,mode){e.preventDefault();if(!sb())return alert('اتصال پایگاه داده برقرار نیست.');const p=phone(document.querySelector('#phoneNumber').value),pw=document.querySelector('#password').value;if(!/^\+989\d{9}$/.test(p))return alert('شماره موبایل را به شکل 09xxxxxxxxx وارد کن.');let r;if(mode==='signup'){const name=document.querySelector('#fullName').value.trim();r=await sb().auth.signUp({phone:p,password:pw,options:{data:{full_name:name}}});if(r.error)return alert('خطای ثبت‌نام: '+r.error.message);if(!r.data.user)return alert('ثبت‌نام انجام نشد.');const pr=await sb().from('profiles').upsert({id:r.data.user.id,full_name:name,phone:p});if(pr.error)return alert('حساب ساخته شد، ولی پروفایل ذخیره نشد: '+pr.error.message);if(r.data.session){window.currentUser=r.data.user;modal.hidden=true;window.updateAuthUI?.()}else alert('حساب ساخته شد. اگر Supabase تأیید شماره را فعال کرده باشد، باید Phone provider را روی حالت بدون تأیید تنظیم کنیم.');return}else r=await sb().auth.signInWithPassword({phone:p,password:pw});if(r.error)return alert('خطای ورود: '+r.error.message);window.currentUser=r.data.user;modal.hidden=true;window.updateAuthUI?.()}
 async function init(){if(!sb())return;const {data}=await sb().auth.getSession();window.currentUser=data.session?.user||null;window.updateAuthUI?.();sb().auth.onAuthStateChange((_e,s)=>{window.currentUser=s?.user||null;window.updateAuthUI?.()})}
 window.openPhoneAuth=()=>form('login');document.querySelector('#authClose')?.addEventListener('click',()=>modal.hidden=true);init();
})();