// Carivo authentication v3: mobile + password, no SMS OTP and no fake email
(function(){
  const sb=()=>window.carivoSupabase;
  const authModal=document.querySelector('#authModal'), authContent=document.querySelector('#authContent');
  function normalizePhone(v){v=(v||'').replace(/[\s-]/g,'');if(v.startsWith('09'))return '+98'+v.slice(1);if(v.startsWith('9')&&v.length===10)return '+98'+v;if(v.startsWith('+98'))return v;return v}
  function showAuth(mode='login'){
    authContent.innerHTML=`<span class="badge">Carivo</span><h2>${mode==='login'?'ورود به حساب':'ساخت حساب جدید'}</h2><form id="authForm">${mode==='signup'?'<label>نام و نام خانوادگی<input id="fullName" autocomplete="name" required placeholder="مثلاً مانی فرحان"></label>':''}<label>شماره موبایل<input id="phoneNumber" inputmode="tel" autocomplete="tel" required placeholder="0912 123 4567"></label><label>رمز عبور<input id="password" type="password" autocomplete="current-password" minlength="6" required placeholder="حداقل ۶ کاراکتر"></label><button class="primary" type="submit">${mode==='login'?'ورود':'ثبت‌نام'}</button></form><button class="auth-link" id="switchAuth">${mode==='login'?'ساخت حساب جدید':'قبلاً حساب دارم'}</button>`;
    authModal.hidden=false;document.querySelector('#authForm').onsubmit=e=>submitAuth(e,mode);document.querySelector('#switchAuth').onclick=()=>showAuth(mode==='login'?'signup':'login');
  }
  async function submitAuth(e,mode){e.preventDefault();const phone=normalizePhone(document.querySelector('#phoneNumber').value),password=document.querySelector('#password').value;if(!/^\+989\d{9}$/.test(phone))return alert('شماره موبایل ایران را به‌صورت 09xxxxxxxxx وارد کن.');if(!sb())return alert('اتصال Supabase آماده نیست.');let result;if(mode==='signup'){const fullName=document.querySelector('#fullName').value.trim();result=await sb().auth.signUp({phone,password,options:{data:{full_name:fullName,phone}}});if(result.error)return alert(result.error.message);if(!result.data.user)return alert('ساخت حساب انجام نشد.');const profile=await sb().from('profiles').upsert({id:result.data.user.id,full_name:fullName,phone});if(profile.error)return alert('حساب ساخته شد اما پروفایل ذخیره نشد: '+profile.error.message);alert('حساب با موفقیت ساخته شد.');if(result.data.session){authModal.hidden=true;window.currentUser=result.data.user;updateAuthUI?.()}else{showAuth('login')}return}else{result=await sb().auth.signInWithPassword({phone,password})}if(result.error)return alert(result.error.message);authModal.hidden=true;window.currentUser=result.data.user;if(typeof updateAuthUI==='function')updateAuthUI()}
  async function init(){if(!sb())return;const {data}=await sb().auth.getSession();window.currentUser=data.session?.user||null;if(typeof updateAuthUI==='function')updateAuthUI();sb().auth.onAuthStateChange((_event,session)=>{window.currentUser=session?.user||null;if(typeof updateAuthUI==='function')updateAuthUI()})}
  window.openPhoneAuth=()=>showAuth('login');document.querySelector('#authClose')?.addEventListener('click',()=>authModal.hidden=true);init();
})();